// machines-data.js
// Массив станков для каталога.
// Станки со status: "hidden" или "draft" не отображаются на сайте.

const machines = [
  {
    id: 1,
    name: "Четырехсторонний станк Боровичи С25-5А",
    type: "Строгальный",
    kind: "Четырёхсторонний",
    manufacturer: "БЗДС",
    country: "Россия",
    year: 2002,
    power: "49,6",
    dimensions: "4800x2000x1500",
    weight: 5200,
    instock: 1,
    images: [
      "/images/wood-machines/borovichi-s25-5a-2002-1.webp",
      "/images/wood-machines/borovichi-s25-5a-2002-2.webp",
      "/images/wood-machines/borovichi-s25-5a-2002-3.webp",
      "/images/wood-machines/borovichi-s25-5a-2002-4.webp"
    ],
    price: 1000000,
    oldPrice: 1299000,
    description: "Продаем пятишпиндельный станок тяжелой серии предназначен для производства различных погонажных изделий и профилированного бруса, в том числе естественной влажности. Рябухи сверху и снизу, подходит для строгания бруса. Станок в отличном состоянии и полностью рабочий!",
    uniqueSpecs: [
      { label: "Количество шпинделей", value: 5 },
      { label: "Ширина заготовки, мм", value: "35-260" },
      { label: "Высота заготовки, мм", value: "12-160" },
      { label: "Скорость работы, м/мин", value: "2-40" },
      { label: "Мин. длина заготовки в потоке, мм", value: 250 },
      { label: "Мин. длина одиночной заготовки, мм", value: 700 },
      { label: "Диаметр выходных патрубков аспирации Ø, мм", value: 150 },
      { label: "Производительность требуемой аспирации, м3/ч", value: "5х2000" },
      { label: "Мощность, кВт", value: "49,6" },
      { label: "Габариты ДxШxВ, мм", value: "4800x2000x1500" },
      { label: "Масса, кг", value: 5200 },
      { label: "Произодитель", value: "БЗДС" },
      { label: "Страна", value: "Россия" },
      { label: "Год", value: 2002 }
    ],
    status: "active"
  },
  {
    id: 2,
    name: "Фрезерный станок ФС",
    type: "Фрезерный",
    kind: "Горизонтальный",
    manufacturer: "Главдревстанкопром",
    country: "СССР",
    year: 1971,
    power: "5",
    dimensions: "1360x1265x1200",
    weight: 880,
    instock: 1,
    images: [
      "images/wood-machines/frezernyy-stanok-fs-1971-1.webp",
      "images/wood-machines/frezernyy-stanok-fs-1971-2.webp",
      "images/wood-machines/frezernyy-stanok-fs-1971-3.webp"
    ],
    price: 75000,
    oldPrice: 105000,
    description: "Продаем отличный и надежный фрезер. Надёжная машина советского времени, выпущенная в 1971 году заводом Главдревстанкопром (г. Днепропетровск). Предназначен для: фрезеровки профилей, торцов, фигурных элементов и других столярных задач. Классическая конструкция с мощным приводом 5 кВт - отличное решением для мастерской с высоким уровнем нагрузки.",
    uniqueSpecs: [
      { label: "Количество шпинделей", value: 1 },
      { label: "Мощность, кВт", value: 5 },
      { label: "Габариты ДxШxВ, мм", value: "1360x1265x1200" },
      { label: "Масса, кг", value: 880 },
      { label: "Произодитель", value: "Главдревстанкопром" },
      { label: "Страна", value: "СССР" },
      { label: "Год", value: 1971 }
    ],
    status: "active"
  },
  {
    id: 3,
    name: "Фрезерный станок ФСШ-1",
    type: "Фрезерный",
    kind: "Горизонтальный",
    manufacturer: "ДСПО",
    country: "СССР",
    year: 1980,
    power: "5",
    dimensions: "1270x1110x1000",
    weight: 810,
    instock: 1,
    images: [
      "images/wood-machines/frezernyy-stanok-fssh-1-1980-1.webp",
      "images/wood-machines/frezernyy-stanok-fssh-1-1980-2.webp",
      "images/wood-machines/frezernyy-stanok-fssh-1-1980-3.webp"
    ],
    price: 75000,
    oldPrice: 105000,
    description: "Продаем отличный и надежный фрезер. Надёжный представитель советской инженерной школы, выпущенный в 1980 году Днепропетровским станкостроительным заводом (ДСПО). Идеально подходит для фрезеровки профилей, торцов, фигурных и сложных элементов. Мощный двигатель 5 кВт, частота вращения шпинделя до 9000 об/мин дает отличную обработку даже твёрдых пород древесины. При весе 810 кг станок стоит монолитно и исключает вибрации, что повышает точность и чистоту обработки. ФСШ-1 — для кто ценит советское качество, долговечность и простоту обслуживания. Он одинаково хорош как для частной мастерской, так и для производственного цеха, где ценится стабильный результат и надёжность, проверенная временем.",
    uniqueSpecs: [
      { label: "Количество шпинделей", value: 1 },
      { label: "Мощность, кВт", value: 5 },
      { label: "Габариты ДxШxВ, мм", value: "1270x1110x1000" },
      { label: "Масса, кг", value: 810 },
      { label: "Произодитель", value: "ДСПО" },
      { label: "Страна", value: "СССР" },
      { label: "Год", value: 1980 }
    ],
    status: "active"
  },
  {
    id: 4,
    name: "Сверлильно-фрезерный станок Biesse Rover 49",
    type: "Фрезерный",
    kind: "с ЧПУ",
    manufacturer: "Biesse",
    country: "Италия",
    year: 1988,
    power: "22,6",
    dimensions: "5300x2440x2240",
    weight: 4600,
    instock: 1,
    images: [
      "images/wood-machines/sverlilno-frezernyy-stanok-rover-49-1.webp",
      "images/wood-machines/sverlilno-frezernyy-stanok-rover-49-2.webp",
      "images/wood-machines/sverlilno-frezernyy-stanok-rover-49-3.webp",
      "images/wood-machines/sverlilno-frezernyy-stanok-rover-49-4.webp",
      "images/wood-machines/sverlilno-frezernyy-stanok-rover-49-5.webp",
      "images/wood-machines/sverlilno-frezernyy-stanok-rover-49-6.webp"
    ],
    videos: [
      "videos/sverlilno-frezernyy-stanok-rover-49.mp4"
    ],
    price: 1500000,
    oldPrice: 1799000,
    description: "Редкая находка для мебельного производства и любых предприятий, где ценят надёжность, стабильность и долговечность оборудования. Этот станок построен так, что один раз настроив на деталь, можно работать круглосуточно без остановки, что делает его идеальным решением для поточного и массового производства. \n\nСтанок работает по координатам X, Y и Z, может фрезеровать криволинейные профили, пазы, выборки и фигурные элементы с высокой точностью. Оснащён 36 вертикальными шпинделями и 12 горизонтальными, что позволяет одновременно выполнять присадку множества отверстий на панели с четырёх сторон — идеальное решение для серийного производства. Два фрезера со стандартными цангами и два с конусом Морзе CM2 обеспечивают возможность работы с фрезами разного диаметра и формы, включая дисковые фрезы до Ø120 мм. Шпиндели фрезеров работают до 18 000 об/мин с мощностью до 5,59 кВт, а дисковые фрезы обеспечивают быстрый и точный рез любой древесины или композитных материалов. Станок рассчитан на непрерывное производство, один раз настроив на деталь, можно работать круглосуточно без остановки. При желании можно за небольшие деньги обновить главный компьютер, и станок будет работать на современном уровне. Для сравнения: аналогичная модель Biesse Rover 2025 года сегодня продаётся от 20 млн рублей. ROVER 49 даёт практически те же возможности за разумные деньги.",
    uniqueSpecs: [
      { label: "Рабочее поле, мм", value: "3200x1304" },
      { label: "Скорость Ось X, м/мин", value: 34 },
      { label: "Скорость Ось Y, м/мин", value: 30 },
      { label: "Скорость Ось Z, м/мин", value: 15 },
      { label: "Мощность сверлильных головок, кВт", value: 1.34 },
      { label: "Хвостовик сверла Ø, мм", value: 10 },
      { label: "Кол-во шпинделей вертикального сверления", value: 36 },
      { label: "Кол-во шпинделей горизонтального сверления (по 4 сторонам панели)", value: 12 },
      { label: "Обороты шпинделей сверления, об/мин", value: 4000 },
      { label: "Направление вращения 2-х фрезеров", value: "передний - правое вращение; задний – левое вращение" },
      { label: "Скорость и мощность фрезера со цангой", value: "12 000 об/мин (1,49 кВт); 18 000 об/мин (2,24 кВт)" },
      { label: "Стандартная цанга для фрезеров Ø, мм", value: "9,5 – 12" },
      { label: "Направление вращения 2-х дисковых фрез", value: "передняя – левое; задняя – правое" },
      { label: "Обороты дисковых фрез, об/мин", value: 12000 },
      { label: "Параметры дисковой фрезы", value: "Ø наружный 120 мм — Ø внутренний 35 мм — толщина 3,5–6 мм" },
      { label: "Мощность двигателей дисковых фрез, кВт", value: "1,86 - 3,73" },
      { label: "Рабочее давление воздуха, бар", value: 6 },
      { label: "Патрубок аспирации Ø, мм", value: 200 },
      { label: "Расход воздуха на аспирацию, м³/ч", value: 2800 },
      { label: "Производительность вакуумного насоса, м³/ч", value: 35 },
      { label: "Габариты ДxШxВ, мм", value: "5300x2440x2240" },
      { label: "Масса, кг", value: 4600 },
      { label: "Произодитель", value: "Biesse" },
      { label: "Страна", value: "Италия" },
      { label: "Год", value: 1988 }
    ],
    status: "active"
  },
  {
    id: 5,
    name: "Пресс для склеивания бруса ПВС-3",
    type: "Пресс",
    kind: "Вертикальный",
    manufacturer: "-",
    country: "Россия",
    year: "-",
    power: "-",
    dimensions: "4100x2400x1600",
    weight: 2000,
    instock: 2,
    images: [
      "images/wood-machines/press-dlya-skleivaniya-brusa-pvs-3-1.webp",
      "images/wood-machines/press-dlya-skleivaniya-brusa-pvs-3-2.webp",
      "images/wood-machines/press-dlya-skleivaniya-brusa-pvs-3-3.webp",
      "images/wood-machines/press-dlya-skleivaniya-brusa-pvs-3-4.webp",
      "images/wood-machines/press-dlya-skleivaniya-brusa-pvs-3-5.webp",
      "images/wood-machines/press-dlya-skleivaniya-brusa-pvs-3-6.webp",
      "images/wood-machines/press-dlya-skleivaniya-brusa-pvs-3-7.webp"
    ],
    price: 1000000,
    oldPrice: 1500000,
    description: "Цена за 2 пресса! Состояние: хорошее, рабочее! По одному не продается. Пресс вертикальный для склеивания бруса и щита, предназначен для сращивания заготовок на гладкую фугу по толщине с целью получения бруса или по ширине с целью получения щита из массивной древесины. Пресс состоит из 2-х частей (каждая из которых по техническим характеристикам соответствует мод. ПВС-3) и устанавливается на специальных домкратах входящих в состав пресса, с помощью которых производится выставка опорных поверхностей 2-х частей в одной плоскости с требуемой точностью. После этого они могут быть соединены технологическими накладками или сваркой. Работа пресса предусматривается в двух режимах: работа на половине пресса (для изделий до 3000 мм.) и работа всего пресса (для изделий до 6000 мм.). Режим работы выбирается переключателем, расположенном на эл. шкафу.",
    uniqueSpecs: [
      { label: "Толщина заготовки, мм", value: "25-50" },
      { label: "Ширина заготовки, мм", value: "25-150" },
      { label: "Длина заготовки, мм", value: "800-3000 / 6000" },
      { label: "Рабочая зона (Мин), мм", value: "700x800" },
      { label: "Рабочая зона (Макс), мм", value: "1000x3000 / 6000" },
      { label: "Макс. усилие гидроцилиндра прессования, кГс", value: 7000 },
      { label: "Наибольшее усилие прижима, кГс", value: 2000 },
      { label: "Количество гидроцилиндров прессования", value: 6 },
      { label: "Наибольший ход прессующего элемента, мм", value: 320 },
      { label: "Наибольший ход прижимной балки, мм", value: 160 },
      { label: "Удельное давление прессования, кг/см² (Хвойные породы)", value: 12 },
      { label: "Удельное давление прессования, кг/см² (Твердолиственные породы)", value: 16 },
      { label: "Количество операторов, обслуживающих пресс", value: "2 чел" },
      { label: "Габариты ДxШxВ, мм", value: "4100x2400x1600" },
      { label: "Масса, кг", value: 2000 },
      { label: "Произодитель", value: "-" },
      { label: "Страна", value: "Россия" },
      { label: "Год", value: "не указан" }
    ],
    status: "active"
  },
  {
    id: 6,
    name: "Копировально-фрезерный станок Griggio G 60",
    type: "Фрезерный",
    kind: "Копировально-фрезерный",
    manufacturer: "Griggio",
    country: "Италия",
    year: "-",
    power: "2,2",
    dimensions: "1900x1200x800",
    weight: 230,
    instock: 1,
    images: [
      "images/wood-machines/kopirovalno-frezernyy-stanok-griggio-g60-1.webp",
      "images/wood-machines/kopirovalno-frezernyy-stanok-griggio-g60-2.webp",
      "images/wood-machines/kopirovalno-frezernyy-stanok-griggio-g60-3.webp",
      "images/wood-machines/kopirovalno-frezernyy-stanok-griggio-g60-4.webp",
      "images/wood-machines/kopirovalno-frezernyy-stanok-griggio-g60-5.webp"
    ],
    price: 185000,
    oldPrice: 210000,
    description: "Станок в хорошем и рабочем состоянии! Надёжный итальянский копировально-фрезерный станок, идеально подходящий для мебельных и столярных цехов. Он легко справляется с фрезеровкой прямых и криволинейных форм, пазов и декоративных элементов по шаблону — от дверных полотен до фасадов и рамок. Две скорости шпинделя (9000 и 18 000 об/мин) позволяют точно работать с деревом, МДФ и фанерой, а прочная конструкция и плавная регулировка стола обеспечивают стабильную и чистую обработку. Это универсальная и долговечная «рабочая лошадка» для тех, кто ценит качество и надёжность.",
    uniqueSpecs: [
      { label: "Размер рабочего стола, мм", value: "800x600" },
      { label: "Вертикальный ход стола, мм", value: 150 },
      { label: "Вертикальный ход шпинделя, мм", value: 80 },
      { label: "Частота вращения шпинделя, об/мин", value: "9000 и 18000" },
      { label: "Макс. расстояние от стола до головки (без патрона), мм", value: 195 },
      { label: "Патрубок аспирации Ø, мм", value: 80 },
      { label: "Мощность, кВт", value: "2,2" },
      { label: "Габариты ДxШxВ, мм", value: "1900x1200x800" },
      { label: "Масса, кг", value: 230 },
      { label: "Произодитель", value: "Griggio" },
      { label: "Страна", value: "Италия" },
      { label: "Год", value: "не указан" }
    ],
    status: "active"
  },
  {
    id: 7,
    name: "Станок для раскроя рулонов",
    type: "Раскройный",
    kind: "Раскрой рулона",
    manufacturer: "-",
    country: "Россия",
    year: "2010",
    power: "3",
    dimensions: "-",
    weight: "-",
    instock: 1,
    images: [
      "images/wood-machines/stanok-dlya-raskroya-rulonov-1.webp",
      "images/wood-machines/stanok-dlya-raskroya-rulonov-2.webp",
      "images/wood-machines/stanok-dlya-raskroya-rulonov-3.webp",
      "images/wood-machines/stanok-dlya-raskroya-rulonov-4.webp"
    ],
    price: 200000,
    oldPrice: 250000,
    description: "Станок отличного качества и неприхотливый  - изготовили сами, силами слесарной комманды на базе имеющегося станка. Продаем в связи не надобностью! Данный станок использовался для дверного производства, а именно для раскроя рулонов покрытия дверей (пленка / бумага / пластик) - на фото видно.",
    uniqueSpecs: [
      { label: "Мощность, кВт", value: 3 },
      { label: "Габариты ДxШxВ, мм", value: "-" },
      { label: "Масса, кг", value: "-" },
      { label: "Произодитель", value: "-" },
      { label: "Страна", value: "Россия" },
      { label: "Год", value: "не указан" }
    ],
    status: "active"
  },
  {
    id: 8,
    name: "Многопильный станок ЦДК 5-3",
    type: "Распиловочный",
    kind: "Дисковый многопильный",
    manufacturer: "ТСЗ",
    country: "Россия",
    year: "1993",
    power: "32,4",
    dimensions: "1930x1780x1630",
    weight: 2150,
    instock: 2,
    images: [
      "images/wood-machines/mnogopilnyy-stanok-cdk-5-3-1.webp",
      "images/wood-machines/mnogopilnyy-stanok-cdk-5-3-2.webp",
      "images/wood-machines/mnogopilnyy-stanok-cdk-5-3-3.webp",
      "images/wood-machines/mnogopilnyy-stanok-cdk-5-3-4.webp",
      "images/wood-machines/mnogopilnyy-stanok-cdk-5-3-5.webp",
      "images/wood-machines/mnogopilnyy-stanok-cdk-5-3-6.webp"
    ],
    price: 300000,
    oldPrice: 350000,
    description: "Станок в хорошем состоянии — всю жизнь отработал в тёплом цеху! В наличии 2 шт.! Многопильный ЦДК 5-3, произведённый Тюменским станкостроительным заводом, — это надёжная и мощная машина (32,4 кВт) для продольного раскроя бруса и досок на обрезные пиломатериалы. Благодаря чугунной станине, продуманной конструкции и виброустойчивому пильному узлу, станок работает спокойно и точно даже при высоких оборотах. Подача заготовок осуществляется широкой конвейерной цепью, обеспечивающей стабильное и ровное движение без пробуксовок. Подходит для пилорам и деревообрабатывающих цехов, где требуется стабильная «рабочая лошадка» для поточного распила заготовок толщиной до 120 мм и шириной до 260 мм.",
    uniqueSpecs: [
      { label: "Толщина заготовки, мм", value: "16-120" },
      { label: "Ширина заготовки, мм", value: "10-260" },
      { label: "Длина заготовки, мм", value: "от 500" },
      { label: "Диаметр применяемых пил, мм", value: "315-400" },
      { label: "Скорость подачи, м/мин", value: "5,5; 10,5; 4,5; 18,5" },
      { label: "Мощность привода пильного вала, кВт", value: 30 },
      { label: "Мощность, кВт", value: "32,4" },
      { label: "Габариты ДxШxВ, мм", value: "1930x1780x1630" },
      { label: "Масса, кг", value: 2150 },
      { label: "Произодитель", value: "ТСЗ" },
      { label: "Страна", value: "Россия" },
      { label: "Год", value: 1993 }
    ],
    status: "active"
  },
  {
    id: 9,
    name: "Четырехсторонний станк Боровичи С25-5А",
    type: "Строгальный",
    kind: "Четырёхсторонний",
    manufacturer: "БЗДС",
    country: "Россия",
    year: 1997,
    power: "49,6",
    dimensions: "4800x2000x1500",
    weight: 5200,
    instock: 1,
    images: [
      "images/wood-machines/borovichi-s25-5a-1997-1.webp",
      "images/wood-machines/borovichi-s25-5a-1997-2.webp",
      "images/wood-machines/borovichi-s25-5a-1997-3.webp",
      "images/wood-machines/borovichi-s25-5a-1997-4.webp"
    ],
    price: 700000,
    oldPrice: 1000000,
    description: "Пятишпиндельный станок тяжелой серии предназначен для производства различных погонажных изделий и профилированного бруса, в том числе естественной влажности. Рябухи сверху и снизу, подходит для строгания бруса. Станок в отличном состоянии и полностью рабочий!",
    uniqueSpecs: [
      { label: "Количество шпинделей", value: 5 },
      { label: "Ширина заготовки, мм", value: "35-260" },
      { label: "Высота заготовки, мм", value: "12-160" },
      { label: "Скорость работы, м/мин", value: "2-40" },
      { label: "Мин. длина заготовки в потоке, мм", value: 250 },
      { label: "Мин. длина одиночной заготовки, мм", value: 700 },
      { label: "Диаметр выходных патрубков аспирации, мм", value: 150 },
      { label: "Производительность требуемой аспирации, м3/ч", value: "5х2000" },
      { label: "Мощность, кВт", value: "49,6" },
      { label: "Габариты ДxШxВ, мм", value: "4800x2000x1500" },
      { label: "Масса, кг", value: 5200 },
      { label: "Произодитель", value: "БЗДС" },
      { label: "Страна", value: "Россия" },
      { label: "Год", value: 1997 }
    ],
    status: "active"
  },
  {
    id: 10,
    name: "Четырехсторонний станк Боровичи С25-4А",
    type: "Строгальный",
    kind: "Четырёхсторонний",
    manufacturer: "БЗДС",
    country: "Россия",
    year: 1994,
    power: "38,6",
    dimensions: "3150x1570x1315",
    weight: 4200,
    instock: 1,
    images: [
      "images/wood-machines/borovichi-s25-4a-1994-1.webp",
      "images/wood-machines/borovichi-s25-4a-1994-2.webp",
      "images/wood-machines/borovichi-s25-4a-1994-3.webp",
      "images/wood-machines/borovichi-s25-4a-1994-4.webp"
    ],
    price: 500000,
    oldPrice: 700000,
    description: "Четырехшпиндельный станок тяжелой серии предназначен для производства различных погонажных изделий и профилированного бруса, в том числе естественной влажности. Станок в отличном состоянии и полностью рабочий!",
    uniqueSpecs: [
      { label: "Количество шпинделей", value: 4 },
      { label: "Ширина заготовки, мм", value: "50-250" },
      { label: "Высота заготовки, мм", value: "12-230" },
      { label: "Скорость работы, м/мин", value: "7-35" },
      { label: "Мин. длина одиночной заготовки, мм", value: 700 },
      { label: "Диаметр выходных патрубков аспирации, мм", value: 150 },
      { label: "Производительность требуемой аспирации, м3/ч", value: "5х2000" },
      { label: "Мощность, кВт", value: "38,6" },
      { label: "Габариты ДxШxВ, мм", value: "3150x1570x1315" },
      { label: "Масса, кг", value: 4200 },
      { label: "Произодитель", value: "БЗДС" },
      { label: "Страна", value: "Россия" },
      { label: "Год", value: 1994 }
    ],
    status: "active"
  },
  {
    id: 11,
    name: "Шлифовальный станок ШЛК-10 Простор",
    type: "Шлифовальный",
    kind: "Калибровальный",
    manufacturer: "Простор",
    country: "Россия",
    year: 2000,
    power: "18",
    dimensions: "1950x1850x1630",
    weight: 2800,
    instock: 1,
    images: [
      "images/wood-machines/shlifovalnyy-stanok-shlk-10-prostor-1.webp",
      "images/wood-machines/shlifovalnyy-stanok-shlk-10-prostor-2.webp",
      "images/wood-machines/shlifovalnyy-stanok-shlk-10-prostor-3.webp",
      "images/wood-machines/shlifovalnyy-stanok-shlk-10-prostor-4.webp"
    ],
    price: 250000,
    oldPrice: 300000,
    description: "Станок в хорошем и рабочем состоянии! Станок ШЛК-10 широколенточный с конвейерной подачей заготовки предназначен для калибрования и шлифования плоских параллельных поверхностей щитовых деталей.",
    uniqueSpecs: [
      { label: "Толщина заготовки, мм", value: "5-100" },
      { label: "Ширина заготовки, мм", value: "до 900" },
      { label: "Длина заготовки, мм", value: "от 360" },
      { label: "Длина шлифовальной ленты, мм", value: 1900 },
      { label: "Ширина шлифовальной ленты, мм", value: 1000 },
      { label: "Скорость шлифовальной ленты, м/сек", value: 25 },
      { label: "Скорость подачи, м/мин", value: 10 },
      { label: "Давление пневмосети, минимальное, кг/см2", value: 4 },
      { label: "Расход потребляемого воздуха, м3/мин", value: "0,15" },
      { label: "Уровень рабочего стола от пола, мм", value: 900 },
      { label: "Мощность, кВт", value: 18 },
      { label: "Габариты ДxШxВ, мм", value: "1950x1850x1630" },
      { label: "Масса, кг", value: 2800 },
      { label: "Произодитель", value: "Простор" },
      { label: "Страна", value: "Россия" },
      { label: "Год", value: 2000 }
    ],
    status: "active"
  },
  {
    id: 12,
    name: "Шлифовальный станок ШлПС-6М",
    type: "Шлифовальный",
    kind: "Ленточный",
    manufacturer: "Кодос",
    country: "Россия",
    year: 1995,
    power: "2,2",
    dimensions: "3500x1500x1500",
    weight: 450,
    instock: 2,
    images: [
      "images/wood-machines/shlifovalnyy-stanok-shlps-6m-1.webp",
      "images/wood-machines/shlifovalnyy-stanok-shlps-6m-2.webp",
      "images/wood-machines/shlifovalnyy-stanok-shlps-6m-3.webp",
      "images/wood-machines/shlifovalnyy-stanok-shlps-6m-4.webp",
      "images/wood-machines/shlifovalnyy-stanok-shlps-6m-5.webp",
      "images/wood-machines/shlifovalnyy-stanok-shlps-6m-6.webp",
      "images/wood-machines/shlifovalnyy-stanok-shlps-6m-7.webp"
    ],
    price: 75000,
    oldPrice: 130000,
    description: "Станки в хорошем состоянии — всю жизнь отработали в тёплом цеху! *В наличии 2 шт!* Станок ШлПС-6М предназначен для шлифования плоских поверхностей щитовых деталей из массивной древесины и мебельных щитов, в том числе облицованных шпоном и покрытых полиэфирным лаком узкой шлифовальной лентой на подвижном столе с утюжком.",
    uniqueSpecs: [
      { label: "Толщина заготовки, мм", value: "до 300" },
      { label: "Ширина заготовки, мм", value: "до 1000" },
      { label: "Длина заготовки, мм", value: "не огранич." },
      { label: "Размеры шлифовальной ленты, мм", value: "6760х100-160" },
      { label: "Скорость резания, м/с", value: 20 },
      { label: "Мощность, кВт", value: "2,2" },
      { label: "Габариты ДxШxВ, мм", value: "3500x1500x1500" },
      { label: "Масса, кг", value: 450 },
      { label: "Произодитель", value: "Кодос" },
      { label: "Страна", value: "Россия" },
      { label: "Год", value: 1995 }
    ],
    status: "active"
  },
  {
    id: 13,
    name: "Ленточная пила по дереву Centauro SP 500",
    type: "Распиловочный",
    kind: "Ленточный",
    manufacturer: "Centauro",
    country: "Италия",
    year: 2004,
    power: "1,8",
    dimensions: "1910x905x630",
    weight: 230,
    instock: 1,
    images: [
      "images/wood-machines/lentochnaya-pila-centauro-sp-500-1.webp",
      "images/wood-machines/lentochnaya-pila-centauro-sp-500-2.webp",
      "images/wood-machines/lentochnaya-pila-centauro-sp-500-3.webp",
      "images/wood-machines/lentochnaya-pila-centauro-sp-500-4.webp",
      "images/wood-machines/lentochnaya-pila-centauro-sp-500-5.webp",
      "images/wood-machines/lentochnaya-pila-centauro-sp-500-6.webp",
      "images/wood-machines/lentochnaya-pila-centauro-sp-500-7.webp"
    ],
    price: 349000,
    oldPrice: 496000,
    description: "Сocтояние отличное, рaбoтaли на станке не много - только точечные и какие-то разовые операции, требующие ручного распила! Ленточнaя пилa по дереву Сеntaurо SР-500 (Италия) - это профессиональный станок для продольного, поперечного и криволинейного распила древесины. Максимально удобная для работы конструкции. Станок выдает обработку древесины на высоком и качественном уровне.",
    uniqueSpecs: [
      { label: "Макс. высота заготовки, мм", value: 300 },
      { label: "Размеры рабочего стола, мм", value: "500x700" },
      { label: "Длина пильного полотна, мм", value: "3860-3945" },
      { label: "Макс. ширина и толщина пильного полотна, мм", value: "30x0,5" },
      { label: "Диаметр шкивов, мм", value: 500 },
      { label: "Скорость вращения шкивов, об/мин", value: 930 },
      { label: "Наклонный чугунный стол, гр (°)", value: "до 45°" },
      { label: "Патрубок аспирации Ø, мм", value: 100 },
      { label: "Торможение шкивов", value: "ножной тормоз" },
      { label: "Мощность, кВт", value: "1,8" },
      { label: "Габариты ДxШxВ, мм", value: "1910x905x630" },
      { label: "Масса, кг", value: 230 },
      { label: "Произодитель", value: "Centauro" },
      { label: "Страна", value: "Италия" },
      { label: "Год", value: 2004 }
    ],
    status: "active"
  },
  {
    id: 14,
    name: "Сверлильно-пазовальный станок с ЧПУ Yuetong MDK 4120 NC",
    type: "Долбежный",
    kind: "Сверлильно-пазовальный",
    manufacturer: "Yuetong",
    country: "Китай",
    year: 2007,
    power: "7",
    dimensions: "2540x2270x1620",
    weight: 1900,
    instock: 1,
    images: [
      "images/wood-machines/sverlilno-pazovalnyy-stanok-yuetong-mdk-4120-nc-1.webp",
      "images/wood-machines/sverlilno-pazovalnyy-stanok-yuetong-mdk-4120-nc-2.webp",
      "images/wood-machines/sverlilno-pazovalnyy-stanok-yuetong-mdk-4120-nc-3.webp",
      "images/wood-machines/sverlilno-pazovalnyy-stanok-yuetong-mdk-4120-nc-4.webp",
      "images/wood-machines/sverlilno-pazovalnyy-stanok-yuetong-mdk-4120-nc-5.webp",
      "images/wood-machines/sverlilno-pazovalnyy-stanok-yuetong-mdk-4120-nc-6.webp"
    ],
    price: 1200000,
    oldPrice: 1490000,
    description: "Сocтояние отличное, рaбoтaли на станке мало - только разовые операции под заказные двери! Станок предназначен специально для проведения фрезерных операций при изготовлении пазов и отверстий различного назначение (установка фурнитуры дверного полотна/коробки: механизм замка, накладка замка, личинка, ручка, петли).",
    uniqueSpecs: [
      { label: "Макс. ширина заготовки, мм", value: 1000 },
      { label: "Макс. длина заготовки, мм", value: 2200 },
      { label: "Толщина заготовки, мм", value: "30-60" },
      { label: "Количество шпинделей, шт.", value: 6 },
      { label: "Обороты шпинделей, об/мин", value: 12000 },
      { label: "Мощность, кВт", value: 7 },
      { label: "Габариты ДxШxВ, мм", value: "2540x2270x1620" },
      { label: "Масса, кг", value: 1900 },
      { label: "Произодитель", value: "Yuetong" },
      { label: "Страна", value: "Китай" },
      { label: "Год", value: 2007 }
    ],
    status: "active"
  },
  {
    id: 15,
    name: "Кромкооблицовочный станок Artech Lato 23s Biesse",
    type: "Кромкооблицовочный",
    kind: "Односторонний",
    manufacturer: "Biesse",
    country: "Италия",
    year: 2007,
    power: "7",
    dimensions: "3690x1400x1195",
    weight: 1000,
    instock: 1,
    images: [
      "images/wood-machines/Biesse-Artech-Lato-23s.webp",
      "images/wood-machines/Biesse-Artech-Lato-23s-2.webp"
    ],
    videos: [
      "videos/Biesse-Artech-Lato-23s.mov"
    ],
    price: 750000,
    oldPrice: 849000,
    description: "Автоматический односторонний кромочный станок LATO приклеивает и обрабатывает плоскую кромку в рулоне (из меламиновой бумаги, ПВХ, ABS, шпона) или в полосках (массивное дерево) к деревянным панелям, ДСП, МДФ, а также к многослойной деревянной плите. Скорость 10м/мин, кромка 0.4-3 мм, торцевание, фрезерование свесов, циклевание, полирование. Данный станок 2007 года выпуска, Италия, куплен новым. Практически не эксплуатировался, можно сказать новый станок с минимальным пробегом. Продаем так как данным станком не пользуемся. Прекрасное техническое и внешнее состояние.",
    uniqueSpecs: [
      { label: "Высота заготовки, мм", value: "10-45" },
      { label: "Высота кромки, мм", value: "13-50" },
      { label: "Мин.толщина кромки в рулоне, мм", value: "0,4-3" },
      { label: "Макс.толщина кромки в массиве, мм", value: 8 },
      { label: "Макс.сечение массива, мм", value: "8x45" },
      { label: "Величина выступа панели с подающего ремня, мм", value: 25 },
      { label: "Мин.длина обрабатываемой панели, мм", value: 140 },
      { label: "Мин.ширина обрабатываемой панели (с длиной 150 мм), мм", value: 85 },
      { label: "Мин.ширина обрабатываемой панели (с длиной 250 мм), мм", value: 50 },
      { label: "Скорость подачи цепного механизма, м/мин, мм", value: 10 },
      { label: "Патрубок аспирации Ø, мм", value: 120 },
      { label: "Давление в пневмосистеме, бар", value: 7 },
      { label: "Емкость клеевого бачка, л", value: 3 },
      { label: "Виды плоских кромок в рулоне", value: "Меламиновая бумага, ПВХ, ABS, шпон" },
      { label: "Виды плоских кромок в полосках", value: "Массивное дерево" },
      { label: "Виды обрабатываемых кромкой заготовок", value: "Деревянные панели, ДСП, МДФ, деревянные плиты" },
      { label: "Мощность, кВт", value: 10 },
      { label: "Габариты ДxШxВ, мм", value: "3690x1400x1195" },
      { label: "Масса, кг", value: 900 },
      { label: "Произодитель", value: "Biesse" },
      { label: "Страна", value: "Италия" },
      { label: "Год", value: 2007 }
    ],
    status: "active"
  },
  {
    id: 16,
    name: "Двухшпиндельный фрезерный станок Бакаут СФ 003",
    type: "Фрезерный",
    kind: "Горизонтальный",
    manufacturer: "Бакаут",
    country: "Россия",
    year: "-",
    power: "11,2",
    dimensions: "1425x1350x755",
    weight: 440,
    instock: 1,
    images: [
      "images/wood-machines/frezernyy-stanok-bakaut-sf-003.webp",
      "images/wood-machines/frezernyy-stanok-bakaut-sf-003-2.webp",
      "images/wood-machines/frezernyy-stanok-bakaut-sf-003-3.webp",
      "images/wood-machines/frezernyy-stanok-bakaut-sf-003-4.webp"
    ],
    price: 250000,
    oldPrice: 300000,
    description: "Продаем двухшпиндельный фрезерный станок Бакаут СФ 003, предназначенный для фрезерования криволинейных кромок деталей из древесины по копиру (мы делали арочные царги дверей и фасадов – на последнем фото пример изделия). Станок имеет два шпинделя, вращающихся в противоположном направлении, что позволяет обрабатывать криволинейные поверхности без сколов и выровов - с учетом расположения волокон. Шпиндели имеют возможность регулировки по высоте ± 5 мм. Рекомендуется для обработки по шаблонам концевыми профильными фрезами замкнутых фигурных пазов на фасадах дверей, мебельных, строительных и других подобных изделий из натуральной древесины. Состояние: отличное, практически не эксплуатировался, можно сказать новый станок. Продаем так как данным станком не пользуемся.",
    uniqueSpecs: [
      { label: "Количество шпинделей", value: 2 },
      { label: "Диаметр шпинделей посадочный, мм", value: 40 },
      { label: "Высота шпинделей под фрезу, мм", value: 85 },
      { label: "Частота вращения шпинделей, об./мин", value: 6000 },
      { label: "Расстояние между шпинделями, мм", value: 700 },
      { label: "Смещение шпинделей по высоте, мм", value: 10 },
      { label: "Мощность, кВт", value: "11,2" },
      { label: "Габариты ДxШxВ, мм", value: "1425x1350x755" },
      { label: "Масса, кг", value: 440 },
      { label: "Произодитель", value: "Бакаут" },
      { label: "Страна", value: "Россия" },
      { label: "Год", value: "не указан" }
    ],
    status: "active"
  },
  {
    id: 17,
    name: "Двухшпиндельный фрезерный станок Бакаут СФ 003",
    type: "Фрезерный",
    kind: "Горизонтальный",
    manufacturer: "Бакаут",
    country: "Россия",
    year: "-",
    power: "11,2",
    dimensions: "1425x1350x755",
    weight: 440,
    instock: 1,
    images: [
      "images/wood-machines/frezernyy-stanok-bakaut-sf-003(2).webp",
      "images/wood-machines/frezernyy-stanok-bakaut-sf-003(2)-2.webp",
      "images/wood-machines/frezernyy-stanok-bakaut-sf-003(2)-3.webp",
      "images/wood-machines/frezernyy-stanok-bakaut-sf-003(2)-4.webp"
    ],
    price: 200000,
    oldPrice: 250000,
    description: "Продаем двухшпиндельный фрезерный станок Бакаут СФ 003, предназначенный для фрезерования криволинейных кромок деталей из древесины по копиру (мы делали арочные царги дверей и фасадов – на последнем фото пример изделия). Станок имеет два шпинделя, вращающихся в противоположном направлении, что позволяет обрабатывать криволинейные поверхности без сколов и выровов - с учетом расположения волокон. Шпиндели имеют возможность регулировки по высоте ± 5 мм. Рекомендуется для обработки по шаблонам концевыми профильными фрезами замкнутых фигурных пазов на фасадах дверей, мебельных, строительных и других подобных изделий из натуральной древесины. Состояние: хорошее, эксплуатировался мало. Продаем так как данным станком не пользуемся.",
    uniqueSpecs: [
      { label: "Количество шпинделей", value: 2 },
      { label: "Диаметр шпинделей посадочный, мм", value: 40 },
      { label: "Высота шпинделей под фрезу, мм", value: 85 },
      { label: "Частота вращения шпинделей, об./мин", value: 6000 },
      { label: "Расстояние между шпинделями, мм", value: 700 },
      { label: "Смещение шпинделей по высоте, мм", value: 10 },
      { label: "Мощность, кВт", value: "11,2" },
      { label: "Габариты ДxШxВ, мм", value: "1425x1350x755" },
      { label: "Масса, кг", value: 440 },
      { label: "Произодитель", value: "Бакаут" },
      { label: "Страна", value: "Россия" },
      { label: "Год", value: "не указан" }
    ],
    status: "active"
  },
  {
    id: 18,
    name: "Веерная вайма SROJ & LES CERKNICA SLR 6/6",
    type: "Пресс",
    kind: "Веерный",
    manufacturer: "SROJ & LES",
    country: "Словения",
    year: "2002",
    power: "-",
    dimensions: "-",
    weight: "-",
    instock: 1,
    images: [
      "images/wood-machines/veernaya-vayma-sroj--les-cerknica-slr-66.webp",
      "images/wood-machines/veernaya-vayma-sroj--les-cerknica-slr-66-2.webp",
      "images/wood-machines/veernaya-vayma-sroj--les-cerknica-slr-66-3.webp"
    ],
    price: 270000,
    oldPrice: 300000,
    description: "Продаем веерную вайму шести пролётную для склейки щита Stroj & Les (Производство Словения). Модель SLR 6/6. Год выпуска 2002. Клеит щит размером 2400 × 800 мм. Хорошее состояние. Очень качественное оборудование по разумной цене.",
    uniqueSpecs: [
      { label: "Макс. длина заготовки, мм", value: 2400 },
      { label: "Макс. ширина заготовки, мм", value: 800 },
      { label: "Толщина склеиваемого щита, мм", value: "25-90" },
      { label: "Количество секций, шт.", value: 6 },
      { label: "Количество зажимов, шт.", value: 6 },
      { label: "Усилие на зажим, кН (кг)", value: "1-10 (100-1000)" },
      { label: "Потребление воздуха, л/с", value: 15 },
      { label: "Макс. нагрузка на секцию, кг", value: 150 },
      { label: "Мощность, кВт", value: "-" },
      { label: "Габариты ДxШxВ, мм", value: "-" },
      { label: "Масса, кг", value: "-" },
      { label: "Произодитель", value: "SROJ & LES" },
      { label: "Страна", value: "Словения" },
      { label: "Год", value: 2002 }
    ],
    status: "active"
  },
  {
    id: 19,
    name: "Станок для резки багета Alfamacchine T350",
    type: "Торцовочный",
    kind: "Стационарный",
    manufacturer: "Alfamacchine",
    country: "Италия",
    year: "2007",
    power: "3",
    dimensions: "1550x800x750",
    weight: "380",
    instock: 1,
    images: [
      "images/wood-machines/Alfamacchine-T350.webp",
      "images/wood-machines/Alfamacchine-T350-2.webp"
    ],
    price: 400000,
    oldPrice: 450000,
    description: "Продаем станок Alfamacchine T 350 для производства рам из разнообразного багета, включая багет из алюминия, а также сложные по форме и богато декорированные профили из дерева и пластика. Станок разработан для крупного производства рам из разнообразного багета (МДФ, алюминиевый профиль, а также сложный по форме багет из дерева и пластика). Станок оснащен двумя пилами с фиксированным углом распила (45°) с двух сторон, пневматической системой подачи пильного блока и прижимом заготовки, устройством регулирования скорости, удлинителями стола. Данный станок 2007 года выпуска, Италия, покупался новым. В отличном состоянии – работали мало. Продаем так как данным станком не пользуемся.",
    uniqueSpecs: [
      { label: "Диаметр пилы, мм", value: 350 },
      { label: "Ширина обработки, мм", value: "80x100" },
      { label: "Высота обработки, мм", value: "80x80" },
      { label: "Давление в пневматической системе, бар", value: 6 },
      { label: "Расход воздуха, л/ч", value: 5 },
      { label: "Производительность, резов/ч", value: "500-600" },
      { label: "Частота вращения пил, об/мин", value: 2800 },
      { label: "Мощность, кВт", value: 3 },
      { label: "Габариты ДxШxВ, мм", value: "1550x800x750" },
      { label: "Масса, кг", value: 380 },
      { label: "Произодитель", value: "Alfamacchine" },
      { label: "Страна", value: "Италия" },
      { label: "Год", value: 2007 }
    ],
    status: "active"
  },
  {
    id: 20,
    name: "Сверлильно-пазовальный станок СВПГ-2А ДСПО",
    type: "Долбежный",
    kind: "Сверлильно-пазовальный",
    manufacturer: "ДСПО",
    country: "Россия",
    year: "1993",
    power: "2",
    dimensions: "1496x724x1115",
    weight: "525",
    instock: 1,
    images: [
      "images/wood-machines/sverlilno-pazovalnyy-stanok-svpg-2a-dspo.webp",
      "images/wood-machines/sverlilno-pazovalnyy-stanok-svpg-2a-dspo-2.webp",
      "images/wood-machines/sverlilno-pazovalnyy-stanok-svpg-2a-dspo-3.webp"
    ],
    price: 135000,
    oldPrice: 155000,
    description: "Продем сверлильно-пазовальный станок СВПГ-2А ДСПО (Днепропетровский станкостроительный завод) для выборки пазов и сверления отверстий круглой и овальной формы, может быть использован для изготовления деталей мебели. Станок предназначен для выборки пазов и сверления отверстий одновременно в двух изделиях из древесины. Станина станка цельнолитая, коробчатой формы. На станине смонтированы: два стола с прижимами, работающими на сжатом воздухе, с гидравлическим регулированием скорости рабочей подачи. Столы имеют горизонтальную рабочую подачу и вертикальное настроечное перемещение. Обработка заготовок на станке производится методом фрезерования концевыми фрезами с осевой и радиальной подачами одновременно при пазовании и только с осевой подачей при сверлении сверлами. Данный станок 1993 года выпуска. Состояние хорошее, рабочее. Продаем так как данным станком не пользуемся.",
    uniqueSpecs: [
      { label: "Количество шпинделей", value: 2 },
      { label: "Макс. толщина заготовки, мм", value: 125 },
      { label: "Макс. ширина фрезеруемого паза, мм", value: 30 },
      { label: "Макс. длина фрезеруемого паза, мм", value: 125 },
      { label: "Макс. диаметр высверливаемого отверстия, мм", value: 30 },
      { label: "Макс. глубина высверливаемого отверстия, мм", value: 90 },
      { label: "Макс. расстояние от оси шпинделя до стола, мм", value: "10-120" },
      { label: "Поворот стола, град", value: "±25°" },
      { label: "Точность обработки по любой оси на длине 100 мм, не более, мм", value: "0,15" },
      { label: "Макс. скорость подачи стола, м/мин", value: 3 },
      { label: "Мощность, кВт", value: 2 },
      { label: "Габариты ДxШxВ, мм", value: "1496x724x1115" },
      { label: "Масса, кг", value: 525 },
      { label: "Произодитель", value: "ДСПО" },
      { label: "Страна", value: "Россия" },
      { label: "Год", value: 1993 }
    ],
    status: "active"
  }
  ,
  {
    id: 21,
    name: "Фрезерный станок ФСШ-1а",
    type: "Фрезерный",
    kind: "Горизонтальный",
    manufacturer: "Главдревстанкопром",
    country: "СССР",
    year: "-",
    power: "5",
    dimensions: "1360x1265x1200",
    weight: 880,
    instock: 1,
    images: [
      "images/wood-machines/frezernyy-stanok-fssh-1a.webp",
      "images/wood-machines/frezernyy-stanok-fssh-1a-2.webp",
      "images/wood-machines/frezernyy-stanok-fssh-1a-3.webp",
      "images/wood-machines/frezernyy-stanok-fssh-1a-4.webp"
    ],
    price: 105000,
    oldPrice: 134000,
    description: "Продаем отличный и надежный фрезер. Надёжная машина советского времени, выпущенная заводом Главдревстанкопром (г. Днепропетровск). Предназначен для: фрезеровки профилей, торцов, фигурных элементов и других столярных задач. Классическая конструкция с мощным приводом 5 кВт - отличное решением для мастерской с высоким уровнем нагрузки.",
    uniqueSpecs: [
      { label: "Мощность, кВт", value: 5 },
      { label: "Габариты ДxШxВ, мм", value: "1360x1265x1200" },
      { label: "Масса, кг", value: 880 },
      { label: "Производитель", value: "Главдревстанкопром" },
      { label: "Страна", value: "СССР" },
      { label: "Год", value: "-" }
    ],
    status: "active"
  }
  ,
  {
    id: 22,
    name: "Фрезерный станок ФСШ-1А(К)",
    type: "Фрезерный",
    kind: "Горизонтальный",
    manufacturer: "КСЗ",
    country: "Россия",
    year: 2000,
    power: "4,2",
    dimensions: "1270x1100x1000",
    weight: 860,
    instock: 1,
    images: [
      "images/wood-machines/frezernyy-stanok-fssh-1ak.webp",
      "images/wood-machines/frezernyy-stanok-fssh-1ak-4.webp",
      "images/wood-machines/frezernyy-stanok-fssh-1ak-2.webp",
      "images/wood-machines/frezernyy-stanok-fssh-1ak-3.webp"
    ],
    price: 105000,
    oldPrice: 134000,
    description: "Продаем отличный и надежный фрезер. Надёжная отечественная машина, выпущенная на Кировском станкостроительном заводе. Станок предназначен для выполнения разнообразных фрезерных работ по дереву с ручной подачей, нарезки простых шипов с помощью шипорезной каретки. Классическая конструкция с мощным приводом 4,2 кВт - отличное решением для мастерской с высоким уровнем нагрузки.",
    uniqueSpecs: [
      { label: "Мощность, кВт", value: "4,2" },
      { label: "Габариты ДxШxВ, мм", value: "1270x1100x1000" },
      { label: "Масса, кг", value: 860 },
      { label: "Производитель", value: "КСЗ" },
      { label: "Страна", value: "СССР" },
      { label: "Год", value: 2000 }
    ],
    status: "active"
  },
  {
    id: 23,
    name: "Форматно-раскроенный станок Giben matic standard",
    type: "Распиловочный",
    kind: "Форматно-раскроечный",
    manufacturer: "GIBEN",
    country: "Италия",
    year: "-",
    power: "7,5",
    dimensions: "6000х3000х1300",
    weight: 3500,
    instock: 1,
    images: [
      "images/wood-machines/formatno-raskroennyy-stanok-giben-matic-standard.webp",
      "images/wood-machines/formatno-raskroennyy-stanok-giben-matic-standard-2.webp",
      "images/wood-machines/formatno-raskroennyy-stanok-giben-matic-standard-3.webp",
      "images/wood-machines/formatno-raskroennyy-stanok-giben-matic-standard-4.webp",
      "images/wood-machines/formatno-raskroennyy-stanok-giben-matic-standard-5.webp",
      "images/wood-machines/formatno-raskroennyy-stanok-giben-matic-standard-6.webp"
    ],
    price: 820000,
    oldPrice: 875000,
    description: "Продаем форматно-раскроенный станок, произведенный заводом GIBEN в Италии. Состояние - хорошое, полностью рабочее. Станок отличается высокой точностью, безопасностью и чистотой реза - рез получается финишным, за счет наличия основной и подрезной пилы. Станок имеет 4 диапазона положения пильного узла. Ему не нужно каждый раз возвращаться в исходное положение, если вы пилите короткие заготовки. Это серьезно сокращает время цикла. Работа на станке безопасна, потому что во время самого реза оператор не имеет прямого контакта с разрезаемым материалом, а заготовка прижимается сверху прижимной балкой с помощью сжатого воздуха. Активация прижимной балки и подача пилы осуществляется с помощью ножной педали. Станок может работать в автоматическом и полуавтоматическом цикле. Станок подходит для работы с плитным материалом и деревом. Станок массивный, прочный и надежный.",
    uniqueSpecs: [
      { label: "Диаметр основной пилы, мм", value: 350 },
      { label: "Диаметр подрезной пилы, мм", value: 125 },
      { label: "Макс. ширина резки, мм", value: 1200 },
      { label: "Макс. длина резки, мм", value: 4200 },
      { label: "Макс. высота резки (основной пилы), мм", value: 70 },
      { label: "Макс. высота резки (подрезной пилы), мм", value: 2 },
      { label: "Скорость пильного диска, об/мин", value: 3800 },
      { label: "Скорость подачи, м/мин", value: 7 },
      { label: "Патрубок аспирации Ø, мм", value: 250 },
      { label: "Мощность, кВт", value: "7,5" },
      { label: "Габариты ДxШxВ, мм", value: "6000х3000х1300" },
      { label: "Масса, кг", value: 3500 },
      { label: "Производитель", value: "GIBEN" },
      { label: "Страна", value: "Италия" },
      { label: "Год", value: "-" }
    ],
    status: "active"
  },
  {
    id: 24,
    name: "Станок торцовочный ЦCТ - 01 КОДОС",
    type: "Торцовочный",
    kind: "Стационарный",
    manufacturer: "КОДОС",
    country: "Россия",
    year: 2008,
    power: "3",
    dimensions: "3880х1100х860",
    weight: 400,
    instock: 1,
    images: [
      "images/wood-machines/stanok-tortsovochnyy-tsct-01-kodos.webp",
      "images/wood-machines/stanok-tortsovochnyy-tsct-01-kodos-2.webp",
      "images/wood-machines/stanok-tortsovochnyy-tsct-01-kodos-3.webp"
    ],
    price: 150000,
    oldPrice: 176000,
    description: "Продаем станок торцовочный ЦCТ - 01 пневматический с нижним расположением пилы для поперечного раскроя строганных заготовок на планки, для последующей зашиповки штучного паркета, а также устанавливается в линии сращивания. Прижим материала производится автоматически верхним упором перед подъемом пилы за счет общего пневмоцилиндра; конструкция прижима исключает образование сколов на поверхности заготовки; для безопасности работы применяется двуручное управление, электродинамическое торможение и система блокировок, отключающих станок. Станок может также использоваться для поперечного раскроя и торцовки деревянных деталей. Область применения - предприятия и цеха для производства паркета, столярно-строительных изделий, стандартного домостроения и других производств. Рабочий цикл осуществляется за счет пневмопривода. Управление пневмоцилиндрами осуществляется ножной пневмопедалью. Пневматическая схема собрана из импортных комплектующих. Состояние - хорошее, рабочее. Столы в комплекте имеются.",
    uniqueSpecs: [
      { label: "Толщина обрабатываемого материала, мм", value: "15 - 100" },
      { label: "Ширина обрабатываемого материала, мм", value: "20 - 200" },
      { label: "Длина обрабатываемого материала, мм", value: "700 - 6000" },
      { label: "Длина детали, выпиливаемой по упору, мм", value: "400 - 3000" },
      { label: "Наибольший диаметр пилы, мм", value: 400 },
      { label: "Частота вращения пилы, об/мин", value: 3000 },
      { label: "Мощность, кВт", value: 3 },
      { label: "Габариты ДxШxВ, мм", value: "3880х1100х860" },
      { label: "Масса, кг", value: 400 },
      { label: "Производитель", value: "КОДОС" },
      { label: "Страна", value: "Россия" },
      { label: "Год", value: 2008 }
    ],
    status: "active"
  }
];